// src/pages/Tql/showChart.vue
<template>
    <v-sheet class="tql-form" color="transparent" height="100%">
        <v-sheet ref="rBodyEl" color="transparent" height="100%">
            <v-sheet v-html="sText" class="tql-chart-form" color="transparent"></v-sheet>
        </v-sheet>
    </v-sheet>
</template>
<script setup="setup" lang="ts" name="Login">
import { defineProps, ref, onMounted, defineExpose } from 'vue';
import showChart from '@/plugins/eChart.ts';

const props = defineProps({
    pData: {
        type: Object,
        default: Object,
    },
});

const sText = ref();

const init = async () => {
    const sTheme = props.pData.theme === '-' ? `westeros` : props.pData.theme;
    let divScripts = document.getElementsByTagName('head')[0];

    let newScript = document.createElement('script');
    newScript.src = `/web/echarts/themes/${props.pData.theme === '-' ? `westeros` : props.pData.theme}.js`;

    if (divScripts) {
        divScripts.appendChild(newScript);
    }

    sText.value = ` <div class="chart_container">
            <div class="chart_item" id="${props.pData.chartID}" style="width:${props.pData.style.width};height:${props.pData.style.height};"></div>
        </div>`;

    setTimeout(() => {
        showChart(props.pData, sTheme);
    }, 100);
};
onMounted(() => {});
defineExpose({ init });
</script>
<style lang="scss" scoped>
.popup__input-content {
    display: flex;
    justify-content: end;
    padding: 4px 8px;
    align-items: center;
    .combobox-select {
        margin: 0 4px;
    }
    div {
        font-size: 14px;
        font-weight: 600;
        display: flex;
        align-items: center;
        margin-right: 8px;
    }
}
.tql-chart-form {
    justify-content: center;
    align-items: center;
}
</style>
<style lang="scss">
.tql-form .chart_container {
    margin-top: 30px;
    display: flex;
    align-items: center;
    .chart_item {
        margin: unset;
    }
}
</style>

// src/components/tql/ShowChart.tsx
import { useState, useEffect } from 'react';
import showChart from '@/plugin/eCharts';

interface ShowChartProps {
    pData: any;
    pIsCenter?: boolean;
}

export const ShowChart = (props: ShowChartProps) => {
    const { pData, pIsCenter } = props;
    const [sText, setText] = useState<string>('');
    const sTheme = pData.theme === '-' ? 'vintage' : pData.theme;

    useEffect(() => {
        init();
    }, [pData]);

    const init = async () => {
        const sValue = ` <div className="chart_container">
                <div className="chart_item" id="${pData.chartID}" style="width:${pData.style.width};height:${pData.style.height};margin:${pIsCenter ? 'auto' : 'initial'}"></div>
            </div>`;
        setText(sValue);

        setTimeout(() => {
            showChart(pData, sTheme);
        }, 100);
    };

    return (
        <div className="tql-form">
            <div dangerouslySetInnerHTML={{ __html: sText }} style={{ display: 'flex' }} className="tql-chart-form"></div>
        </div>
    );
};
